# permissions for end users to edit fufus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fufu-editor-role
rules:
- apiGroups:
  - cat.huozj.io
  resources:
  - fufus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cat.huozj.io
  resources:
  - fufus/status
  verbs:
  - get
