---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cat.huozj.io
  resources:
  - fufus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cat.huozj.io
  resources:
  - fufus/finalizers
  verbs:
  - update
- apiGroups:
  - cat.huozj.io
  resources:
  - fufus/status
  verbs:
  - get
  - patch
  - update
