apiVersion: v1
kind: Namespace
metadata:
  name: fufu

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: fufu
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: prepare-webcontent
        image: alpine
        env:
        - name: FUR_COLOR
          value: "orange"
        - name: BREED
          value: "stray"
        - name: AGE
          value: "6"
        - name: WEIGHT
          value: "5"
        command: ["/bin/sh", "-c"]
        args: ["wget https://raw.githubusercontent.com/ZhengjunHUO/kubebuilder/main/k8s/nginx/index.html.tmpl && apk add gettext && envsubst '$FUR_COLOR $BREED $AGE $WEIGHT' < index.html.tmpl > /mnt/index.html"] 
        volumeMounts:
        - mountPath: /mnt
          name: homedir
          readOnly: false
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
          name: homedir
          readOnly: true
      volumes:
      - name: homedir
        emptyDir:
          sizeLimit: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: fufu
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: fufu
spec:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
